wb_labels:
 - IT技术
 - 互联网
 - 人文
 - 休闲娱乐
 - 体育
 - 养生
 - 军事
 - 动漫
 - 动物
 - 医疗
 - 历史
 - 奢侈品
 - 娱乐明星
 - 婚庆
 - 孕产
 - 宗教
 - 宠物
 - 家装家居
 - 小技巧
 - 情感
 - 房地产
 - 搞笑
 - 摄影拍照
 - 收藏
 - 政府政务
 - 教育
 - 数码
 - 旅游出行
 - 时尚
 - 星座命理
 - 植物
 - 民俗
 - 汽车
 - 法律
 - 游戏
 - 电影
 - 电视剧
 - 社会
 - 科学科普
 - 综艺
 - 美妆
 - 美食
 - 职场
 - 育儿
 - 设计
 - 读书作家
 - 财经
 - 运动健身
 - 音乐
